project:
  type: website
  output-dir: _site

website:
  title: "Ebola BVD 2026: Outbreak Sitreps"
  description: "Automated translation of Ebola-BVD 2026 outbreak situation reports"
  site-url: "https://kathsherratt.github.io/bvd-sitreps"
  navbar:
    right:
      - icon: github
        href: https://kathsherratt.github.io/bvd-sitreps
      - icon: house-fill
        text: " "
        href: index.qmd
  announcement:
    icon: cone-striped
    dismissable: true
    position: below-navbar
    content: '**Under development**'
    type: warning
  open-graph: true
format:
  html:
    theme: cosmo
    toc: true
    comments:
      hypothesis: true
