---
title: "SitRep 013"
subtitle: "Report date 2026-05-27"
date: 2026-05-27
sitrep: "013"
pdf_md5: 91492c9d4c3db1fa0fc07073fd180716
model: agy:gemini-3.8-flash-low
translate_key: "91492c9d4c3db1fa0fc07073fd180716:c95d366fc47db0685de85290691c3ec5:2b47b40403025e32e12927f461c2f1e4:gemini-3.1-pro-preview:da5ff90cf9667d64f15f0f0a0c7b6c29:agy:gemini-3.8-flash-low"
lang: en
---

::: {.callout-caution}
Machine translation from the French original with Google Gemini, with no human review. Check the original before relying on any figure.
:::

Affected provinces (3) ITURI, NORD-KIVU & SUD-KIVU

Affected Health Zones (13) ITURI: Aru, Bunia, Kilo, Mongbwalu, Nizi, Nyankunde and Rwampara NORD-KIVU: Butembo, Goma, Oicha, Kalunguta and Katwa SUD-KIVU: Miti-Murhesa

Reporting date 27 May 2026

Publication date 28 May 2026

[PHOTO]

0. HIGHLIGHTS

• First recovered case (F, 32-year-old PPL (person released from treatment (discharged patient)) admitted on 18 May to CH Salama for fever, headaches and body aches.

Transferred to HGR (general referral hospital) Rwampara on 20 May 2026;

• A first patient recovered from MVE (Ebola virus disease) was recorded at the Ebola Treatment Centre (CTE (Ebola treatment centre)) of the Rwampara health zone.

• Reception today of a 4-module GeneXpert/Radione machine as well as 2 000 cartridges intended for diagnosis.

• Escape of a confirmed case managed at CH Salama.

I. CONTEXT

The Province of Ituri is situated in the North-East of the Democratic Republic of the Congo and shares a long border with Uganda and South Sudan.

For more than two decades, it has been confronted with a chronic humanitarian crisis linked to armed conflicts and recurrent displacements of populations.

It has an estimated population of more than 8 million inhabitants, among whom more than one million internally displaced persons.

In September 2018, this province was affected by an outbreak of the Ebola virus disease that was raging in the neighbouring province of Nord-Kivu.

The Mongbwalu health zone is one of the 36 health zones of the province of Ituri.

Considered as the starting point of the outbreak, it is situated in the territory of Djugu where several armed groups operate.

It is situated 70 km from Bunia, capital of the province of Ituri, with frequent movements of populations towards Uganda.

This locality has a particularity of having several work sites that attract populations coming from the other territories of the province and from neighbouring provinces.

[FIGURE: Figure 1. Chronology of events of the Ebola-Bundibugyo virus disease outbreak.]

[FIGURE: Figures 2 & 3. Spatial distribution of confirmed cases of MVE by affected health zone and in the three affected provinces as of 27 May 2026.]

II. EPIDEMIOLOGICAL SITUATION UPDATE

• No new confirmed case was reported for the day of 27 May 2026.

• Three provinces are currently affected, namely those of Ituri, Nord-Kivu and Sud-Kivu.

• Cumulative total of confirmed cases 27 May 2026: 125 cases of which 110 in Ituri, 14 in Nord-Kivu and 1 in Sud-Kivu.

• ITURI: epicentre with 7/36 ZS (health zone) affected (Aru, Bunia, Kilo, Rwampara, Mongbwalu, Nizi and Nyankunde)

• NORD-KIVU: 5/35 ZS affected (Goma, Butembo, Oicha, Kalunguta and Katwa) SUD-KIVU: 1/34 ZS affected (Miti-Murhesa)

III. RESPONSE ACTIONS

IV.1. COORDINATION

• Holding of a strategic meeting at the Prime Minister's Office aiming at the mobilisation of financial and logistical resources for the response.

• Organisation of bilateral meetings by the strategic coordination dedicated to resource mobilisation with key partners.

• Holding of the first meeting of the planning pillar at the COUSP (public health emergency operations centre).

IV.2. EPIDEMIOLOGICAL SURVEILLANCE

• Implementation of field surveillance activities: reporting and validation of alerts, case investigations, active case finding, contact listing and follow-up, as well as the retrospective documentary review of cases and deaths.

• Training of PCI (infection prevention and control) actors on the general aspects of MVE and surveillance activities, including case mapping.

• For the day of 27 May 2026, 118 alerts were reported, 98 (83,0%) were investigated and 51 (52,0%) were validated, of which 35 (68,6%) were sampled (partial data).


| Provinces | Health zones | No. of suspected cases* | No. of suspected deaths* | No. of Confirmed cases* | No. of contacts* |
|---|---|---|---|---|---|
| Ituri | Aru | 4 | 1 | 1 | 0 |
| Ituri | Bambu | 6 | 2 | 0 | 244 |
| Ituri | Bunia | 249 | 48 | 37 | 404 |
| Ituri | Kilo | 8 | 2 | 1 | 41 |
| Ituri | Mongbwalu | 339 | 88 | 20 | 222 |
| Ituri | Nizi | 6 | 2 | 2 | 220 |
| Ituri | Nyankunde | 45 | 11 | 10 | 397 |
| Ituri | Rwampara | 228 | 69 | 33 | 697 |
| Ituri | Samples without form | 0 | 0 | 6 | 0 |
| Ituri | Subtotal | 885 | 223 | 110 | 2225 |
| Nord-Kivu | Butembo | 7 | 0 | 5 | 28 |
| Nord-Kivu | Goma | 0 | 0 | 1 | 74 |
| Nord-Kivu | Kalunguta | 13 | 0 | 2 | ND |
| Nord-Kivu | Karisimbi |  |  |  | 181 |
| Nord-Kivu | Katwa | 0 | 0 | 4 | 111 |
| Nord-Kivu | Kyondo | 0 | 0 | 0 | 16 |
| Nord-Kivu | Oicha | 0 | 0 | 2 | ND |
| Nord-Kivu | Subtotal | 20 | 0 | 14 | 410 |
| Sud-Kivu | Miti Murhesa | 1 | 0 | 1 | ND |
| Sud-Kivu | Subtotal | 1 | 0 | 1 | 0 |
| Total | Total | 906 | 223 | 125 | 2635** |

: Table II. Distribution of suspected and confirmed cases and deaths of Ebola virus disease in the health zones of the DPS Ituri, Nord-Kivu and Sud Kivu as of 27 May 2026


*These data are likely to change after harmonisation of data at different levels of the health pyramid with the incident management system.

** contact follow-up still remains sub-optimal.

Surveillance at Points of Entry and Control Points (PoE/PoC):

• Provision of 4 3 000-litre tanks, of which 2 at the Dele PoC and 2 at Mudzibala by the partner Samaritan’s Purse.

• Identification of 5 PoCs in the Mongbwalu ZS: Poipo, Pluto, Njebi, Pont-Frigo and Kilo in order to make them operational.


| Indicators at PoE/PoC | TOTAL |
|---|---|
| Travellers passing through the PoE/PoC | 14 662 |
| Travellers screened | 14 530 |
| Travellers who washed their hands | 14 314 |
| Travellers sensitised on MVE | 14 530 |
| Contacts listed | 0 |
| Alerts reported | 0 |

: Table III. Summary of data at PoE/PoC of 27/05/2026


IV.3. LABORATORY

• Reception of 2 016 RADIONE tests, extraction kits, personal protective equipment and other supplies with the support of WHO.

• Fitting out for the cold chain of the radione reagents at the Bunia laboratory.

• A confirmed patient had their test (resamplings) negative as of 27 May 2026.

The latter was declared recovered and discharged from the CTE during the same day.

• Furthermore, among the 203 samples shipped to Kinshasa, 95 were analysed and 24 returned positive (distribution by health zone in progress).

[PHOTO]


| Key indicators | 27/05/2026 | Total |
|---|---|---|
| Samples received | 73* | 774 |
| Resamplings (control) | 8 (4 negative) | 8 |
| No. of samples analysed | 3 | 648 |
| Positivity rate | 0 | 19,2% |
| No. of positive cases | 0 | 125 |

: Table IV. Update on the laboratory situation as of 27/05/2026


*these data are only for the Bunia laboratory.

IV.4. INFECTION PREVENTION & CONTROL

• Continuation of the training of trainers and supporting partners on the complete PCI package (D2).

1. Bunia ZS

• Provision and reception of 45kg of chlorine to the PCI pillar.

• Decontamination of 2 households in Solenyama

• 3 SDBs conducted on 3 alert cases (1 HGR-Bunia and 2 CS Aero).

2. Rwamapara ZS

• Briefing of 2 healthcare providers on bed spacing (Maternity) (CS Rwamapara).

3. Nyakunde ZS

• 2 SDBs conducted on 2 alert cases and 2 Decontaminations in the community.

4. Aru ZS

• 1 SDB conducted on 1 alert case.

• Disinfection of the Bakitha hall.

5. Mongwalu ZS

• 7 SDBs conducted on 9 Alert cases (1 HGR-Mongwalu, 1 AS (health area) Lodjo, 4 AS Mongbwalu, 2 AS Ceca 20).

[PHOTO]

IV.5. HOLISTIC CARE

• Briefing of providers on the assessment of nutritional status.

• Handover of MUAC for nutritional activities.

• Field visit for the monitoring of CTE works.

• Mental health and psychosocial interventions:

(i) Announcement: 4 deaths followed by psychological support for families regarding the SDB;

(ii) Briefing of clinical psychologists on the announcement of confirmed cases and deaths;

• Continuity of care: 2 teams of assessors were briefed on the evaluation of health facilities in the RWAMPARA health zone;


| Indicators and Variables | HGR BUNIA (12 Beds: 08 S and 03 C ) | HGR RWAMPARA (18 Beds: 08 C and 10 S) | CME (27 Beds : 08 Conf and 19 S ) | HGR MUNGBWALU (40 Beds: 12 C and 28 S ) | HGR NYAKUNDE | CT BAMBU | CT HEAL AFRICA (Nord-kivu) 19 beds | TOTAL and Occup rate |
|---|---|---|---|---|---|---|---|---|
| Brought forward | 14 | 8 | 22 | 10 | 39 | 6 | 2 | 101 |
| New PPL | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 1 |
| Admissions Other | 2 | 2 | 5 | 1 | 0 | 3 | 0 | 13 |
| Discharges Recovered | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Discharges Deceased | 1 | 1 | 1 | 2 | 1 | 0 | 0 | 6 |
| Discharges Non-Cases | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Discharges Escaped | 3 | 0 | 0 | 1 | 0 | 0 | 0 | 4 |
| Discharges Transferred | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Hospitalised Patients Total | 12 | 9 | 26 | 9 | 38 | 9 | 0 | 103 |
| Hospitalised Patients New Confirmed Cases | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 1 |
| Hospitalised Patients Former Confirmed Cases | 1 | 0 | 0 | 0 | 9 | 1 | 1 | 12 |
| Hospitalised Patients Suspects | 11 | 8 | 26 | 9 | 29 | 8 | 1 | 92 |
| Hospitalised Patients Suspect < 5 years | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Bed occupancy rate Suspects | 11/12(91,6%) | 8/10(80%) | 26/27(96%) | 9/28(32%) | ND | ND | ND | 70,1% |
| Bed occupancy rate Confirmed | 1/3 (33,3%) | 1/8 (12%) |  | 0/12 (0%) | ND | ND | ND | 8,7% |

: Table V. Movement of patients in healthcare facilities as of 27/05/2026


S: Suspects C: confirmed

IV.6. RCCE

Management of rumours around SDBs, decontamination and drop in health facility attendance.

• 21 journalists from the local media of Bunia (Radios, TV and online media) committed to communicating only information

• Commitment of 31 APA (burgomaster and heads of different departments) of the SHARI Commune (Bunia ZS) to prevent and manage the infodemic and community resistance

BUNIA ZS: 478 persons sensitised at the central market of Bunia on preventive measures against MVE, including 323 women and 135 men.

Deployment of communication materials in strategic locations of Bunia (MURONGO National Airport and Bunia Central Market).

RWAMPARA ZS: Sensitisation of two traditional practitioners who treated two deceased patients in the Shari AS and preparation of a field visit with the Surveillance pillar to deepen investigations

❖ Interpersonal communication

Bunia and Rwampara ZS:

• 7 323 persons reached by sensitisation messages during door-to-door visits conducted by Red Cross volunteers: 1 024 men, 1 286 women, 2626 girls, 2 327 boys.

Bunia ZS:

• 3 662 pupils including 2 414 girls, 1 248 boys sensitised in 5 schools on preventive measures against MVE.

Nizi ZS: Educational discussions with 90 RECO (community health worker) including 30 in the LINGO AS, 30 in the LOPA AS and 30 in the LOPA Mission AS on preventive measures against MVE and referral of patients to the nearest healthcare facilities.

IV.7. LOGISTICS

• Supply of PCI consumables and materials to category 1 health facilities

• Monitoring of the progress of CTE construction works at HGR BUNIA;

• Monitoring of installation works of 3 tents at CME/BUNIA.

• Inspection of plumbing and electrical installations at the Provincial Laboratory.

IV.8. SECURITY

• The security situation in the city of Bunia (Bunia and Rwampara ZS) is relatively calm

• Security briefing for newly deployed teams.

IV. CHALLENGES

• Reluctance regarding post-mortem samples: Formal refusal of families to have diagnostic tests (swabs) performed on the bodies of the deceased in mortuaries.

• Absence of standardized Transit Centres and Ebola Treatment Centres in Ituri.

• Weakness of Contact Tracing and Training Deficit of Actors

• Persistence of gaps in the identification and rigorous surveillance of contact cases at the level of active and high-risk health zones.

• Shortage in isolation structures: Total absence of essential medicines at the Ebola Treatment Centre (CTE) and in the isolation block of Rwampara and Nyankunde.

• Failure in the supply of referral hospitals: Lack of provision of Generic Essential Medicines (MEG) within the four targeted General Referral Hospitals (HGR), weakening the overall care of patients.

• Lack of PCI materials (PPE, DLM, chlorine) in Nord Kivu

• Low reporting of alerts by zones in the 3 affected Provinces (Ituri, Nord-Kivu and Sud-Kivu);

• Insufficiency of financial resources to support all response pillars in the affected ZS;

• Difficulty in transporting samples to the laboratories in Goma and Kinshasa.

• Spread of rumours and proliferation of traditional treatment recipes.

• Absence of communication materials and tools.

• Low diagnostic capacity

• Insecurity in the intervention health zones (Fire at the Rwampara CT (transit centre), Mongbwalu.

V. OUTLOOK

• Training of providers on the use of RADIONE PCR

• Training of providers on MVE surveillance and SBC in the affected and high-risk ZS of the three affected provinces;

• Training of Community Workers on MVE surveillance and SBC in the affected and high-risk ZS of the ITURI province.

• Finalise the development of the research protocol and data collection tools on community perception of MVE, the response and actors in the health zones affected by the MVE outbreak.

[PHOTO]

For the National Institute of Public Health (INSP (National Institute of Public Health)) of the DRC

The Director General of the INSP

Dr MWAMBA KAZADI Dieudonné

E-mail: dieudonne.mwamba@insp.cd

Tel.: +243 816 040 145

The PHEOC Coordinator

Prof NGANDU Christian

E-mail: Christian.ngandu@insp.cd

Tel.: +243998091915

The Incident Manager

Prof Pierre AKILIMALI

E-mail: pierre.akilimali@insp.cd

Tel.: +243815800288

FOR ANY ADDITIONAL INFORMATION, PLEASE CONTACT

## Source

- [Original PDF (French), INSP](https://insp.cd/wp-content/uploads/2026/05/SitRep_MVE_RDC_NA°013_27_05_2026_ES-IM4.pdf)
- [French transcription](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/corpus/fr/013.md)
- [013_table_01_tableau_ii_repartition_des_cas_deces_sus](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/013_table_01_tableau_ii_repartition_des_cas_deces_sus.csv)
- [013_table_02_tableau_iii_synthese_de_donnees_au_poe_p](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/013_table_02_tableau_iii_synthese_de_donnees_au_poe_p.csv)
- [013_table_03_tableau_iv_point_sur_la_situation_de_lab](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/013_table_03_tableau_iv_point_sur_la_situation_de_lab.csv)
- [013_table_04_tableau_v_mouvement_des_malades_dans_les](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/013_table_04_tableau_v_mouvement_des_malades_dans_les.csv)
