---
title: "SitRep 058"
subtitle: "Report date 2026-07-11"
date: 2026-07-11
sitrep: "058"
pdf_md5: 2766dff2db75e2d8f40b1187d13204ad
model: agy:gemini-3.8-flash-low
translate_key: "2766dff2db75e2d8f40b1187d13204ad:c95d366fc47db0685de85290691c3ec5:2b47b40403025e32e12927f461c2f1e4:gemini-3.1-pro-preview:da5ff90cf9667d64f15f0f0a0c7b6c29:agy:gemini-3.8-flash-low"
lang: en
---

::: {.callout-caution}
Machine translation from the French original with Google Gemini, with no human review. Check the original before relying on any figure.
:::

[PHOTO]

Affected provinces (5) HAUT-UELE, ITURI, NORD-KIVU, SUD-KIVU & TSHOPO
Affected health zones (42)
• Haut-Uélé (1/13): Wamba
• Ituri (26/36) : Aru, Aungba, Bambu, Bunia, Damas, Drodro, Gety, Kilo, Komanda, Lita, Logo, Mambasa, Mangala, Mongbwalu, Nizi, Nyankunde, Rimba, Rwampara, Tchomia, Kambala, Nia-Nia, Fataki, Mandima, Lolwa, Boga and Ariwara.
• Nord-Kivu (11/34) : Beni, Butembo, Goma, Kalunguta, Katwa, Kyondo, Oicha, Masereka, Vuhovi, Mabalako and Musienene.
• Sud-Kivu (1/34) : Miti-Murhesa
• Tshopo (3/23): Makiso-Kisangani, Lubunga and Mangobo
Reporting date 11 July 2026
Publication date 12 July 2026

Public Health Emergency Operations Centre
« COUSP (public health emergency operations centre) DRC »
Incident Management System MVE-17

Situation Report on the 17th EBOLA Virus Disease Outbreak /DRC
SitRep N°058/MVB_11/07/2026

[PHOTO]

* Data updated following the cleaning and harmonisation process of the DHIS2 database, including the consolidation of information from health zones, laboratories and case management structures.
**Suspected deaths occurring in the community are subject to in-depth investigation with a view to possible reclassification (Non-cases, probable cases).

# 1. HIGHLIGHTS

• Over the past 24 hours, 53 new confirmed cases and 30 deaths (66,6% community) were recorded in the provinces of Ituri (45 cases and 27 deaths) and Nord-Kivu (8 cases and 2), highlighting the progression of the epidemiological situation of the 17th outbreak of Ebola Virus Disease (MVE (Ebola virus disease)) in the Democratic Republic of the Congo.
Thus, the cumulative total stands at 1 926 confirmed cases and 702 deaths, representing an overall case fatality rate of 36,4%.

• A new health zone affected in the province of Ituri, namely: Ariwara health zone.

• Ten (10) deaths were recorded among MVE patients in the CTE (Ebola treatment centre)/CT (transit centre) in Ituri (4 at CTE Mongbwalu, 2 at CTE Elikya, 1 at CTE Rwampara, 1 at CT Sota and 1 at CT HGR (general referral hospital) Nia-Nia) and in Nord-Kivu (1 at CTE Butembo).

• Twelve (12) patients with Ebola virus disease in the province of Ituri (3 at CTE CME, 2 at CTE Mongbwalu, 3 at CTE ISTM and 4 at CT Sota) were declared cured after testing negative on control tests, including one patient who was under clinical trial at CTE CME.

• Receipt of 18 motorbikes, donated by UNICEF, to strengthen the mobility of community actors in high-risk health zones

• Investigations continue in the province of Tshopo and Haut Uele.
Note that all Tshopo cases (n=4) are imported cases from Nia-Nia.
However, they were allocated to the health zones of Kisangani where they were detected.

# 2. EPIDEMIOLOGICAL AND OPERATIONAL CONTEXT

Declared on 15 May 2026, the outbreak of Ebola virus disease due to Bundibugyo ebolavirus continues to evolve in a complex humanitarian and security context.
Initially detected in the Health Zone of Mongbwalu (Ituri), it spread to three provinces (Ituri, Nord-Kivu and Sud-Kivu), affecting 38 Health Zones.
Population movements, insecurity, artisanal mining activities and cross-border trade with Uganda and South Sudan foster transmission and complicate response operations.
Multisectoral coordination continues to limit the spread of the outbreak and strengthen public health interventions.

[FIGURE: Figure 1. Chronology of events of the Ebola-Bundibugyo virus disease outbreak]

# 3. DETAILED EPIDEMIOLOGICAL ANALYSIS

## 3.1 Spatial distribution and active hotspots as of 11 July 2026


| Province | Confirmed cases | Deaths (confirmed) | Case fatality | Affected health zones | New confirmed cases (24h) |
|---|---|---|---|---|---|
| Ituri* | 1745 | 601* | 34,4% | 26 out of 36 (72,2 %) | 45 |
| Nord-Kivu | 173 | 97 | 56,1% | 11 out of 34 (32,4 %) | 8 |
| Sud-Kivu | 3 | 1 | 33,3% | 1 out of 34 (2,9 %) | 0 |
| Haut-Uélé | 1 | 1 | 100,0% | 1 out of 13 (7,7 %) | 0 |
| Tshopo | 4 | 2 | 50,0% | 3 out of 23 (13,0%) | 0 |
| Total | 1 926 | 702 | 36,4% | 42 out of 117 | 53 |

: Table 1. Distribution of confirmed cases and deaths by affected province as of 11 July 2026.


*9 deaths in Ituri were recorded among MVE patients (previous confirmed cases) in the CTE/CT

At the end of the day of 11 July 2026, a new health zone was affected, Ariwara, in the province of Ituri over the past 24 hours.
The cumulative number of affected health zones now stands at 42 out of 117 (section 3.1).
Since 26 May 2026, the province of Sud-Kivu has recorded no confirmed cases, suggesting an absence of recent transmission.
As of 7 July 2026, the province of Sud-Kivu officially crossed the milestone of 42 consecutive days without notification of a new confirmed case, corresponding to twice the maximum incubation period of the virus.
This crucial milestone marks the end of the period of heightened surveillance and opens the way to the official declaration of the end of the outbreak in this province, subject to maintaining residual epidemiological vigilance.

## 3.2 Temporal analysis:

An increasing number of confirmed cases is observed from one week to the next, reflecting continuous transmission of the disease in the community.
The intensification of public health actions in epidemiological and biological surveillance (decentralisation of diagnostic capacities) confirmed continuous and increased community transmission in W25.
Compared to all weeks in which cases have been recorded since the beginning of the outbreak, W25, W26 and W27 continue to see growth in the number of reported cases, with more than 300 weekly cases.

[FIGURE: Number of confirmed cases by week of notification]

## 3.3 Epidemic mapping

[FIGURE: Figures 2 and 3. Spatial distribution of confirmed MVE cases by affected health zones and across the three affected provinces as of 11 July 2026.]


| Province / Health zone | Cumulative confirmed cases (n) | Cumulative confirmed deaths (n) | Case fatality (CFR %) |
|---|---|---|---|
| ITURI | 1745 | 601 | 34,5% |
| Bunia | 507 | 160 | 31,6% |
| Rwampara | 393 | 90 | 22,9% |
| Mongbwalu | 336 | 177 | 52,7% |
| Nyankunde | 99 | 25 | 25,3% |
| Nizi | 121 | 47 | 38,8% |
| Lita | 48 | 19 | 39,6% |
| Komanda | 27 | 8 | 29,6% |
| Bambu | 31 | 10 | 32,3% |
| Kilo | 9 | 1 | 11,1% |
| Mangala | 50 | 29 | 58,0% |
| Tchomia | 19 | 4 | 21,1% |
| Damas | 5 | 0 | 0,0% |
| Aungba | 6 | 2 | 33,3% |
| Rimba | 4 | 0 | 0,0% |
| Aru | 3 | 1 | 33,3% |
| Mambasa | 5 | 4 | 80,0% |
| Logo | 7 | 0 | 0,0% |
| Drodro | 4 | 3 | 75,0% |
| Gety | 1 | 0 | 0,0% |
| Kambala | 2 | 2 | 100,0% |
| Nia-Nia | 36 | 12 | 33,3% |
| Fataki | 4 | 1 | 25,0% |
| Mandima | 8 | 3 | 37,5% |
| Lolwa | 1 | 1 | 100,0% |
| Boga | 1 | 1 | 100,0% |
| Ariwara | 1 | 1 | 100,0% |
| Other zones not yet identified | 17 | 0 | 0,0% |
| NORD-KIVU | 173 | 97 | 56,1% |
| Butembo | 44 | 21 | 47,7% |
| Katwa | 71 | 47 | 66,2% |
| Beni | 30 | 20 | 66,7% |
| Oicha | 3 | 2 | 66,7% |
| Kalunguta | 2 | 1 | 50,0% |
| Kyondo | 7 | 3 | 42,9% |
| Goma | 1 | 0 | 0,0% |
| Masereka | 3 | 0 | 0,0% |
| Vuhovi | 1 | 1 | 100,0% |
| Mabalako | 1 | 0 | 0,0% |
| Musienene | 10 | 2 | 20,0% |
| SUD-KIVU | 3 | 1 | 33,3% |
| Miti-Murhesa | 3 | 1 | 33,3% |
| HAUT-UÉLÉ | 1 | 1 | 100,0% |
| Wamba | 1 | 1 | 100,0% |
| TSHOPO | 4 | 2 | 50,0% |
| Makiso-Kisangani | 2 | 2 | 100,0% |
| Mangobo | 1 | 0 | 0,0% |
| Lubunga | 1 | 0 | 0,0% |
| TOTAL | 1926 | 702 | 36,4% |

: Table 2. Distribution of confirmed cases and deaths of Ebola virus disease by province and health zone (11 July 2026)


Over the past 24 hours, 53 new confirmed cases and 29 deaths (68,9% community) were recorded in the provinces of Ituri (45 cases and 27 deaths) and Nord-Kivu (8 cases and 2 deaths), highlighting the progression of the epidemiological situation of the 17th outbreak of Ebola Virus Disease (MVE) in the Democratic Republic of the Congo.
Thus, the cumulative total stands at 1 926 confirmed cases and 701 deaths, representing an overall case fatality rate of 36,4%.

Provincial dynamics and concentration of cases

The province of Ituri alone accounts for 90,9% of cases (n=1 750) and 86,2% of deaths (n=604), representing a crude case fatality rate of 34,5%, making it the epicentre of the outbreak.
The health zones of Bunia (507 cases), Rwampara (393 cases), Mongbwalu (336 cases), Nizi (121) and Nyankunde (99 cases) remain the most affected and account for approximately 83,2% of reported cases at the provincial level and 75,6% at the national level.
In Nizi, the outbreak is currently progressing faster than in the other zones.

Severity of the outbreak in Nord-Kivu

A total of 173 confirmed cases and 97 deaths have been reported in the province of Nord-Kivu since the beginning of the outbreak, representing a crude case fatality rate of 56,1%.
This high case fatality rate is driven by the health zones of Katwa (66,2%), Beni (66,7%) and Butembo (47,7%).
While the other health zones account for only 32,1% of the case fatality rate.
Three health zones lead the notifications in terms of case numbers: Katwa (n=71), followed by Butembo (n=44) and Beni (n=30).

# 4. RESPONSE ACTIONS BY PILLAR

## 4.1 Coordination

National / Ituri & Kinshasa

• Holding of the coordination meeting with technical and financial partners.

• Continuation of response supervision activities in the field.

## 4.2 Epidemiological surveillance


| Indicator | Ituri | Nord-Kivu | Sud-Kivu | Total |
|---|---|---|---|---|
| Carried over (D-1) | 175 | 27 | 0 | 202 |
| New Alerts | 462 | 696 | 12 | 1170 |
| Total Alerts of the day | 637 | 696 | 12 | 1345 |
| Investigated alerts | 471 | 696 | 12 | 1179 |
| Investigation rate | 73,94% | 100,00% | 100,0% | 87,6% |
| Validated live alerts | 118 | 34 | 6 | 158 |
| Validated deceased alerts | 48 | 22 | 0 | 70 |
| Total suspected cases of the day | 166 | 56 | 6 | 228 |

: Table 3. Management of epidemiological alerts (24h) as of 11 July 2026


During the day of 11 July 2026, a total of 1345 alerts were recorded in the provinces of Ituri, Nord-Kivu and Sud-Kivu, including 1170 new alerts and 202 alerts carried over from the previous day, demonstrating the maintenance of active epidemiological surveillance in the affected provinces.

The majority of alerts were notified in Nord-Kivu, with 696 alerts, or 100 %, compared with 471 alerts, or 73,94 %, in Ituri and 100% in Sud-Kivu.

Among the recorded alerts, 1179 were investigated, representing an overall investigation rate of 87,6 %.
The investigation rate stood at 73,94 % in Ituri and 100% in the other two provinces, highlighting the need to strengthen investigation capacities in the province of Ituri.

Investigations led to the validation of 228 suspected cases, including 158 living persons, or 69,2 %, and 70 deaths, or 30,7 %.
Ituri recorded the largest number of validated suspected cases, with 166 cases, or 35,2 %, compared with 56 cases, or 8,0 %, in Nord-Kivu and 50% in Sud-Kivu.


| Province | Contacts under follow-up (n) | Contacts seen (n) | Follow-up rate (%) |
|---|---|---|---|
| Ituri | 10 450 | 7 886 | 75,5% |
| Nord-Kivu | 2 285 | 2 084 | 91,2% |
| Sud Kivu* | 0 | 0 | NA |
| Total | 12 735 | 9 970 | 78,3% |

: Table 4. Contact tracing of confirmed cases (1) as of 11 July 2026


* End of follow-up for all contacts listed in the province of Sud-Kivu.

As of this day, 11 July, 12 735 contacts were under follow-up in the provinces of Ituri and Nord-Kivu.
Among them, 9 970 were actually seen, corresponding to an overall follow-up rate of 78,3%.
Ituri had the largest number of contacts under follow-up, 10450 (75,5% of the total), with 7886 contacts seen, representing a follow-up rate of 75,5 %.
In Nord-Kivu, 2285 contacts were under follow-up, of whom 2084 (91,2%) were visited.

Follow-up performance is comparable between the two provinces; however, the overall follow-up rate remains below the recommended operational threshold for optimal contact tracing.
Strengthening daily contact tracing, particularly for those who were not seen, remains a priority in order to ensure early detection of secondary cases and limit the risk of community transmission.


| Province | Number of new contacts n | Number of new contacts % | Number of contacts who became suspected n | Number of contacts who became suspected % | Number of contacts discharged at 21 days n | Number of contacts discharged at 21 days % |
|---|---|---|---|---|---|---|
| Ituri | 364 | 75,7% | 13 | 68,4% | 294 | 80,3% |
| Nord-Kivu | 117 | 24,3% | 6 | 31,6% | 72 | 19,7% |
| Total | 481 | 100,0% | 19 | 100,0% | 366 | 100,0% |

: Table 5. Contact tracing of confirmed cases (2) as of 11 July 2026


The day of 11 July closed with 481 new contacts listed, the majority in Ituri 364 (75,7%), while Nord-Kivu listed 117 (24,3%).
Among the contacts followed up, twelve (19) developed signs consistent with the suspected case definition, including thirteen (13) in Ituri, or 68,4 %, and Six (6) in Nord-Kivu, or 31,6 %.
These contacts require immediate investigation and management in accordance with current procedures.

In addition, 366 contacts completed their 21-day follow-up period without developing symptoms compatible with the disease, including 294 in Ituri, or 80,3 %, and 72 in Nord-Kivu, or 19,7 %.

These results reflect the continuation of contact tracing and follow-up activities, while highlighting the need to maintain rigorous surveillance to ensure early detection of secondary cases and rapidly interrupt any potential transmission chain

Update on points of control and points of entry (PoC/PoE) activities

Ituri: Five (5) alerts were notified, including three (3) live alerts and two (2) dead bodies.
Among the live alerts, two (2) were validated, isolated and referred to the CT/CTE, while one (1) was invalidated after reassessment; At PoC Nyamusasi, a 26-year-old man, travelling from Tchomia to Kasenyi, presenting with fever, was validated, isolated and transferred to the CT.

Nord Kivu: Two (2) alerts were notified.
At PoC Kasitu, a 16-year-old boy of Congolese nationality, travelling from Mongamba in Ituri to Butembo, presenting with a fever of 38,5 °C and headache, was notified, investigated and referred to isolation at CS Bundji.


| INDICATORS | Ituri | Nord-Kivu | Overall |
|---|---|---|---|
| Proportion of activated PoC and reinforced PoE | 100% (57/57) | 100,0% (14/14) | 100,0% (71/71) |
| Number of persons passing through PoE/PoC | 90 389 | 53 705 | 144 094 |
| % of travellers screened | 93,9% | 98,0% | 95,4% |
| % of travellers having washed hands | 93,0% | 98,0% | 94,9% |
| % of travellers sensitized | 98,2% | 98,0% | 98,1% |
| Number of alerts notified | 5 | 2 | 7 |
| Number of validated live alerts | 2 | 1 | 3 |
| Number of dead bodies intercepted this day | 2 | 1 | 3 |
| Number of problematic contacts intercepted this day | 0 | 0 | 0 |
| % of validated live alerts referred to CT/CTE | 100,0% | 100,0% | 100,0% |
| % of dead bodies swabbed | 50,0% | 0,0% | 33,3% |
| Number of positive results among referred suspected cases | 0 | 0 | 0 |

: Table 6. Monitoring of indicators at Points of Entry and Points of Control (PoE/PoC), as of 11 July 2026


## 4.3. Laboratory

• Ituri: 227 samples collected and analysed (positivity 19,9%; n=45).

• Nord-Kivu: 123 samples collected and analysed (positivity 6,5%; n=8).

• Sud-Kivu: 6 samples collected and undergoing analysis.

## 4.4. Infection Prevention and Control (PCI (infection prevention and control))

Ituri: Sixty-seven (67) households corresponding to the passage of cases were targeted and 42 were decontaminated within 48 hours, or 62,7%.
The twelve (12) healthcare facilities that accommodated a confirmed case were decontaminated within 48 hours, or 100%.
In addition, 175 healthcare facilities out of 1 170 had triage or pre-triage with a one-way flow, or 15,0%; 45 healthcare facilities out of 678 in high-risk health areas had received a complete PCI kit, or 6,6%; 924 providers out of 1 640 had been trained in Ebola PCI/EHA, or 56,3%; and 208 healthcare facilities out of 1 170 had a 48-hour water storage capacity, or 17,8%.

## 4.5 EDS:

Ituri: Safe and dignified burials: Sixty-eight (68) deaths were to be managed, including 50 alerts of the day and 18 carried over.
Thirty-six (36) EDS were carried out, six (6) deaths were buried without safe precautions by families and 26 were carried over, representing a performance of 53%.
Twenty-four (24) swabs were performed.
A stockout of supplies for EDS teams was reported in the ZS (health zone) of Nizi

Nord-Kivu: Seven (7) bodies were pending from the previous day and 24 death alerts were notified.
In total, 24 bodies were swabbed and secured, 26 safe and dignified burials were conducted and five (5) bodies were carried over; Training of the EDS team of the Kalunguta Health Zone was completed.

## 4.6 Holistic care

Ituri:

• Nine (9) deaths were recorded among MVE patients in the CTE/CT in Ituri (4 at CTE Mongbwalu, 2 at CTE Elikya, 1 at CTE Rwampara, 1 at CT Sota and 1 at CT HGR Nia-Nia).

• Twelve (12) patients with Ebola virus disease in the province of Ituri (3 at CTE CME, 2 at CTE Mongbwalu, 3 at CTE ISTM and 4 at CT Sota) were declared cured after obtaining negative control tests, including one patient who was under clinical trial at CTE CME.

• Three ambulance trips were completed successfully, including two from Lopa to CTE ISTM Nyankunde and one from Sangaki, AS (health area) Mandro, to HGR Bunia.
Three ambulances were operational and one ambulance was non-operational due to a battery problem.

• At the end of the day of 11 July, 936 hot meals were served: 95 to suspected cases, 149 to confirmed cases, 664 to PPL (person released from treatment (discharged patient)) and 28 to accompanying persons.

Patient movement:

• 94 new admissions were recorded in the CTE/CT/CI (isolation centre) across the three provinces, including 67 in Ituri, 21 in Nord-Kivu and 6 in Sud-Kivu according to the latest available data.
Discharges totalled 110 patients.


| Indicator | Ituri | Nord-Kivu | Sud-Kivu | All |
|---|---|---|---|---|
| Patients in bed (D-1) | 544 | 201 | 24 | 769 |
| Total admissions (24h) | 67 | 21 | 6 | 94 |
| Discharges (24h) Deceased (Suspected/Conf.) | 14 | 1 | 0 | 15 |
| Discharges (24h) Non-cases | 42 | 33 | 0 | 75 |
| Discharges (24h) Cured | 12 | 0 | 0 | 12 |
| Discharges (24h) Absconded (Suspected/Conf.) | 8 | 0 | 0 | 8 |
| Discharges (24h) Transferred to HGR | 0 | 0 | 0 | 0 |
| Discharges (24h) Total discharges | 76 | 34 | 0 | 110 |
| Patients in isolation (End of day) | 535 | 188 | 30 | 753 |
| of whom confirmed (NC+AC) | 227 | 21 | 0 | 248 |
| of whom suspected | 308 | 201 | 30 | 539 |
| Overall occupancy rate | 87% | 129,6% | 66,6% | 93,9% |

: Table 7. Movement of patients in healthcare facilities (CTE/CT/CI) as of 11 July 2026


In total, 753 patients were in isolation, including 248 confirmed cases and 539 suspected cases, for an overall bed occupancy rate of 93,9%.


| KEY INDICATORS | ITURI | NORD-KIVU | SUD-KIVU |
|---|---|---|---|
| New confirmed cases admitted to the CTE having received SMSPS (mental health and psychosocial support) interventions | 2 (18,2%) | 0,0% | 0 |
| Confirmed cases undergoing follow-up having received SMSPS interventions | 98 (61,6%) | 0,0% | 0 |
| New suspected cases having received SMSPS interventions | 29 (80,6%) | 0,0% | 2 |
| Suspected cases undergoing follow-up having received SMSPS interventions | 62 (37,3%) | 0,0% | 1 (100,0%) |
| Laboratory results having been announced | 12 |  | 1 |
| Of which positive | 2 | 0 | 0 |
| No. of separated children in crèche having received SMSPS interventions | 6 | 0 | 0 |
| No. of separated children in community having received SMSPS interventions | 0 | 0 | 7 |
| No. of accompanying persons at CTE having received SMSPS interventions | 67 | 0 | 0 |
| No. of PPL having received SMSPS interventions | 26 | 1 | 0 |
| No. of members of households and communities having received SMSPS interventions | 32 | 0 | 0 |
| No. of EDS supported | 2 | 0 | 0 |

: Table 8. Key indicators of mental health and psychosocial support activities as of 11 July 2026


## 4.7 Continuity of care

• 14/36 health zones shared the mapping of partners providing free healthcare in Ituri.

• Implementation of effective free healthcare.

• Provision of essential medicines for PMA and PCA in the other health zones

• Care for non-cases (children, mothers and other vulnerable persons) in service continuity actions.

• Psychosocial support for affected PPL and their dependants

## 4.8 Risk communication and community engagement

Ituri: Two (2) advocacy meetings engaged 58 persons (38 men and 20 women); 3 340 persons were reached during home visits (1 479 men and 1 861 women); 2 649 persons were reached during educational talks and focus groups (1 184 men and 1 465 women); 28 persons were engaged during a community dialogue (23 men and 5 women); and 5 484 persons were reached during 77 mass awareness sessions (2 221 men and 3 263 women.

Community feedback: Twelve (12) pieces of feedback and infodemics were reported, of which ten (10) were captured and two (2) clarified, representing 20% of captured feedback.
Major concerns related to delays by EDS teams, management of community deaths, discharge of a patient from CTE Rwampara, payment of providers, and requests for money for household decontamination.

Support to response pillars

Surveillance: 97 community alerts were escalated, including 70 live alerts and 27 deaths, in the ZS of Bunia, Nyankunde and Rwampara.
Support was also provided for listing 11 contacts at Clinique Gloria and pre-listing around a contact case.

CREC: Twenty-four (24) community mobilisers from the ZS of Nizi and 17 Red Cross volunteers in the ZS of Bunia were briefed on MVE; two radio broadcasts and six spots were produced and broadcast, 36 community radio stations were engaged and 15 posters and IEC materials were distributed.
Support was provided for the decontamination of three households in the ZS of Rwampara, AS Shari.

Nord-Kivu: 405 community actors reported their activities; 7 370 households were visited; 36 819 persons were reached by prevention messages through door-to-door visits; 745 persons were reached during dialogues and educational talks; 2 691 persons were reached in public places; and 27 radio stations broadcast at least one communication format.

Community surveillance and feedback management: 212 alerts of suspected cases were escalated by community actors; three (3) feedback items or infodemics out of five were captured and resolved within 48 hours; 1 262 persons were engaged in community actions; and one community incident was resolved within 48 hours.
In the ZS of Katwa, CREC supported tracing lost-to-follow-up contacts, transferring a suspected patient to the CTE, and preparing households for decontamination.
Mass communication reached 63 students in Katwa and 35 CAC members were briefed in Mabalako.

Specific feedback: In the Kyondo health area, part of the population fears sending patients to the CTE, believing that insufficient staff experience would inevitably lead to patient deaths.
The agreed action consists of strengthening community communication, drawing notably on testimonials from cured individuals.

## 4.9. Logistics

Ituri

• Receipt of 18 motorbikes, donated by UNICEF, to strengthen the mobility of community actors in high-risk ZS; delivery of PCI, Surveillance and PECH supplies to the ZS of Mangala and Lita as well as to CTE Sota; receipt of 10 tonnes of PCI and PECH supplies with support from WHO.
In total, 25 vehicles and five (5) ambulances were made available to the various pillars.
A total of 200 litres of fuel was distributed to operational ambulances and vehicles.

Nord-Kivu

Deployment of teams from the various pillars to the health zones; holding of the section meeting; packing of PCI kits and medicines for case management at Hôpital de Mambangu; continuation of unpacking medicines received from UNICEF; and monitoring the repair of mobile vehicle 103 at the Mutsora garage.

## 4.10. Security

• No new major security incidents were reported in the consolidated presentation of 11 July 2026.
Vigilance remains heightened around PoE/PoC and care facilities.

• Continuation of coordination with political-administrative and security authorities to guarantee access of response teams to high-risk areas.

## 4.10. PSEA (Prevention of Sexual Exploitation and Abuse)

Ituri: Continuation of community awareness on the prevention of sexual exploitation and abuse.

Sixty-two (62) participants, including 45 men and 17 women, were briefed, bringing the cumulative total to 2 250 persons briefed and having signed codes of conduct, including 1 286 men and 964 women.
In total, 107 persons, including 54 women/girls and 53 men/boys, were sensitized, bringing the cumulative total to 12 872 persons sensitized, including 6 944 men and 5 928 women.
PSEA activities were integrated into the ZS of Lita, bringing the number of covered ZS to five: Bunia, Rwampara, Mongbwalu, Aru and Lita.

# 5. MAIN CHALLENGES, IMPACTS AND REQUIRED ACTIONS


| No. | Challenges | Impact | Required actions |
|---|---|---|---|
| 1 | Reluctance regarding post-mortem sampling (EDS / swabs) and community resistance | Delayed confirmation, underestimation of cases, disruption of key activities | Intensify CREC, involvement of religious and community leaders, strengthening team security, add to the number of EDS teams |
| 2 | Insufficient capacity of CTE/CT and saturation in Nord-Kivu (129,6%) | Admission delays, increased risk of nosocomial transmission | Accelerate construction and expansion of CTE, deploy additional temporary structures, improve laboratory result turnaround times |
| 3 | Non-optimal contact tracing performance (78,3% vs 95% target) | Transmission chains not interrupted | Train, deploy and motivate community health workers (RECO (community health worker)), reinforced supervision |
| 4 | Low escalation of alerts in certain affected ZS | Undetected transmission, silent expansion of the outbreak | Strengthen community surveillance, improve escalation and rapid investigation of alerts |
| 5 | Confirmed cases not yet broken down by health zone (17 cases) | Major gaps in the reconstruction of transmission chains | Conduct data reconciliation, prune potential duplicates, and reclassify or specify health zone and status (deaths, cured, active, etc.,) Active field verification |
| 6 | Insufficient supply of essential generic drugs (MEG) and medical inputs | Weakening of overall management | Advocacy and urgent procurement of essential medicines |
| 7 | Insufficient PCI supplies (PPE, chlorine) and limited training | High risk of nosocomial infections (112 HCW cases including 35 deaths, case fatality 31,2%) | Urgent procurement, strengthening of PCI training |
| 8 | Stock of samples not yet analysed (backlog) in the laboratory in Nord-Kivu and late diagnosis | Delayed confirmation, high case fatality (56,1%) | Deploy a laboratory catch-up plan, strengthen diagnostic capacities, improve flow of laboratory data |
| 9 | Insufficient ambulances and isolation structures (gap of 20 centres) | Transfer and isolation delays, increased transmission risk | Urgent deployment of additional logistics and infrastructure |
| 10 | Insufficient coordination and weak utilisation of COUSP frameworks | Operational inefficiency and delayed decisions | Strengthen coordination mechanisms at all levels, operationalise provincial COUSPs |
| 11 | Insufficient financial resources (gap of 20 million USD) | Limitation of implementation across all response pillars | Urgent resource mobilisation, advocacy with partners |
| 12 | Insecurity and limited access (CODECO, ADF) | Restriction of operations, limited access to high-risk areas | Strengthening of security coordination and humanitarian access |
| 13 | Continuity of essential health services (CEHS) compromised | Increase in indirect mortality (non-Ebola) | Effective implementation of free healthcare, strengthening CEHS |
| 14 | High population mobility | High risk of rapid geographical spread | Strengthen surveillance at PoE/PoC and cross-border coordination |


# 6. PHOTOS OF FIELD ACTIVITIES

[PHOTO]

Receipt of 18 motorbikes donated by UNICEF

[PHOTO]

FOR ANY FURTHER INFORMATION, PLEASE CONTACT

For the National Institute of Public Health (INSP (National Institute of Public Health)) of the DRC

The Director General of the INSP
Dr MWAMBA KAZADI Dieudonné
E-mail: dieudonne.mwamba@insp.cd
Tel.: +243 816 040 145

The COU-SP Coordinator
Prof NGANDU Christian
E-mail: Christian.ngandu@insp.cd
Tel.: +243998091915

The Incident Manager
Prof Pierre AKILIMALI
E-mail: pierre.akilimali@insp.cd
Tel.: +243815800288

With technical support from the World Health Organization (WHO), Africa CDC and Bluesquare

## Source

- [Original PDF (French), INSP](https://insp.cd/wp-content/uploads/2026/07/Draft_SitRep_MVE_RDC_N°58_11-07-2026-final.pdf)
- [French transcription](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/corpus/fr/058.md)
- [058_table_01_tableau_1_repartition_des_cas_et_deces_c](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/058_table_01_tableau_1_repartition_des_cas_et_deces_c.csv)
- [058_table_02_tableau_2_repartition_des_cas_et_deces_c](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/058_table_02_tableau_2_repartition_des_cas_et_deces_c.csv)
- [058_table_03_tableau_3_gestion_des_alertes_epidemiolo](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/058_table_03_tableau_3_gestion_des_alertes_epidemiolo.csv)
- [058_table_04_tableau_4_suivi_des_contacts_des_cas_con](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/058_table_04_tableau_4_suivi_des_contacts_des_cas_con.csv)
- [058_table_05_tableau_5_suivi_des_contacts_des_cas_con](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/058_table_05_tableau_5_suivi_des_contacts_des_cas_con.csv)
- [058_table_06_tableau_6_suivi_des_indicateurs_au_point](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/058_table_06_tableau_6_suivi_des_indicateurs_au_point.csv)
- [058_table_07_tableau_7_mouvement_des_patients_dans_le](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/058_table_07_tableau_7_mouvement_des_patients_dans_le.csv)
- [058_table_08_tableau_8_indicateurs_cles_des_activites](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/058_table_08_tableau_8_indicateurs_cles_des_activites.csv)
- [058_table_09](https://github.com/epiforecasts/bvd-sitreps/blob/main/data/csv/058_table_09.csv)
